# Sample setup macro with no visualization

/run/verbose 0
/tracking/verbose 0
/hits/verbose 0
/grdm/verbose 0

## select the geometry
# Default config if you do nothing is currently SuperK
#
# The tube size is fixed for SK to 20 inch
# These are fixed geometries for validation
#/WCSim/WCgeom SuperK

# Some other SuperK options:
/WCSim/WCgeom SNS_FTS_40perCent # 
#/WCSim/WCgeom SNS_FTS_78perCent # 
#/WCSim/WCgeom SuperK
/WCSim/Construct # This must be uncommented in order to construct a new detector configuration.

#Added for the PMT QE option 08/17/10 (XQ)
# 1. Stacking only mean when the photon is generated
# the QE is applied to reduce the total number of photons
# 2. Stacking and sensitivity detector
# In the stacking part, the maximum QE is applied to reduce
# the total number of photons
# On the detector side, the rest of QE are applied according to QE/QE_max
# distribution. This option is in particular important for the WLS
# 3. The third option means all the QE are applied at the detector
# Good for the low energy running.
# 4. Switch off the QE complety, ie. set it at 100%
/WCSim/PMTQEMethod     Stacking_Only
#/WCSim/PMTQEMethod     Stacking_And_SensitiveDetector
#/WCSim/PMTQEMethod     SensitiveDetector_Only
#/WCSim/PMTQEMethod     DoNotApplyQE

#turn on or off the collection efficiency
/WCSim/PMTCollEff on

# command to choose save or not save the pi0 info 07/03/10 (XQ)
/WCSim/SavePi0 false

#choose the Trigger & Digitizer type (and options)
/DAQ/Digitizer SKI
/DAQ/Trigger NDigits
#/DAQ/Trigger NoTrigger

#grab the other DAQ options (thresholds, timing windows, etc.)
/control/execute macros/daq.mac


# default dark noise frequency (and conversion factor) is PMT property (NEW), set in the code.
# Below gives possibility to overwrite nominal values, eg. to switch OFF the Dark Noise.
#/DarkRate/SetDarkRate 0 kHz   #Turn dark noise off
#/DarkRate/SetDarkRate 4.2 kHz #This is the value for SKI set in SKDETSIM.
#/DarkRate/SetDarkRate 8.4 kHz #For 20 inch HPDs and Box and Line PMTs, based on High QE 20 inch R3600 dark rate from EGADS nov 2014
#/DarkRate/SetDarkRate 3.0 kHz #For 12 inch HPDs and Box and Line PMTs, based on High QE 20 inch R3600 dark rate from EGADS nov 2014

# command to multiply the dark rate.
# Convert dark noise frequency before digitization to after digitization by setting suitable factor
# Again, this is now a PMT property and can be overridden here
#/DarkRate/SetConvert 1.367  #For Normal PMT
#/DarkRate/SetConvert 1.119 #For HPDs
#/DarkRate/SetConvert 1.126 #For Box and Line PMTs

# Select which time window(s) to add dark noise to
#/DarkRate/SetDarkMode 0 to add dark noise to a time window starting at
#/DarkRate/SetDarkLow to /DarkRate/SetDarkHigh [time in ns]
#/DarkRate/SetDarkMode 1 adds dark noise hits to a window of
#width /DarkRate/SetDarkWindow [time in ns] around each hit
#i.e. hit time ± (/DarkRate/SetDarkWindow) / 2
/DarkRate/SetDetectorElement tank
/DarkRate/SetDarkMode 1
/DarkRate/SetDarkHigh 100000
/DarkRate/SetDarkLow 0
/DarkRate/SetDarkWindow 4000

#/DarkRate/SetDetectorElement OD
#/DarkRate/SetDarkMode 1
#/DarkRate/SetDarkHigh 100000
#/DarkRate/SetDarkLow 0
#/DarkRate/SetDarkWindow 4000

#Uncomment one of the lines below if you want to use the OGLSX or RayTracer visualizer
#/control/execute macros/visOGLSX.mac
#/control/execute macros/visRayTracer.mac
#/control/execute macros/visOGLQt.mac



## select the input nuance-formatted vector file
## you can of course use your own
#/mygen/generator muline
#/mygen/vecfile inputvectorfile
#/mygen/vecfile h2o.2km.001-009x3_G4.kin
#/mygen/vecfile mu+.out
# define units used for time in kin file
#/mygen/time_unit ns

# Or you can use the G4 Particle Gun
# for a full list of /gun/ commands see:
# http://geant4.web.cern.ch/geant4/G4UsersDocuments/UsersGuides/ForApplicationDeveloper/html/Control/UIcommands/_gun_.html
#/mygen/generator gun

#/gun/particle gamma
#/gun/particle e-
#/gun/particle pi0
#/gun/energy 500 MeV
#/gun/direction 1 0 0 
#/gun/position 0 0 0  

#/gps/direction 1 0 0
#/gps/position 0 0 0

# Or you can use the laser option
# This is equivalent to the gps command, except that the gps particle energies are saved ignoring their mass
# for a full list of /gps/ commands see:
# https://geant4.web.cern.ch/geant4/UserDocumentation/UsersGuides/ForApplicationDeveloper/html/ch02s07.html
# It is used for laser calibration simulation
#/mygen/generator laser
#/gps/particle opticalphoton
#/gps/energy 2.505 eV
#/gps/direction 1 0 0
#/gps/position 0 0 0
#/gps/number 1000
#/gps/ang/type iso
#/gps/ang/mintheta 0 deg
#/gps/ang/maxtheta 30 deg
#/gps/ang/minphi 0 deg
#/gps/ang/maxphi 360 deg

# Or you can use a cosmics generator
# Based on the SuperK flux extrapolated at HyperK site in Mozumi
# Muons are generated according to this flux and their position is extrapolated outside the tank
# Useful to study muons tracks in both OD and ID
#/mygen/generator cosmics
#/mygen/cosmicsfile data/MuonFlux-HyperK-ThetaPhi.dat

# Radioactive option
# IMPORTANT: You need to compile WCSim with cmake in order to use the radioactive decays
# Generate radioactive decay in the water or on the PMTs
#/mygen/generator radioactive
# This window should match the one in biasprofile.dat (see below)
#/mygen/radioactive_time_window 1.e-4
# The following list the different isotope to take into account, where they decay, 
# and what are their activities in the full ID detector (for Water) or in the PMT (for PMT)
#/mygen/isotope Tl208 PMT 2.8
#/mygen/isotope Bi214 PMT 27.
#/mygen/isotope K40 PMT 94.
#/mygen/isotope Bi214 water 264. ### HK
#Clear the source and tell GPS to make multiple vertices
#/gps/source/clear

# Radon option
# IMPORTANT: You need to compile WCSim with cmake in order to use the radioactive decays
# Generate Bi214 decay in the water following a Model extracted from SK-IV solar data
#/mygen/generator radon
# This window should match the one in biasprofile.dat if time bias is used (see below)
#/mygen/radioactive_time_window 1.e-4
# Needed if time bias is not used, in order to keep timing below one sec.
#/DAQ/RelativeHitTime true
# The following set which scenario is used to scale SK model to HK
#/mygen/radon_scaling A # 	Relative scaling with respect to full ID volume (Pessimistic, should be default for now)
#/mygen/radon_scaling B #	Absolute scaling with respect to ID border (Optimistic)
#/mygen/radon_scaling 0 #	Uniform distribution 
#/mygen/radon_symmetry 1 #	Divide the detector in x slices using the theta symmetry
#Clear the source and tell GPS to make multiple vertices
#/gps/source/clear

# Or you can use the G4 General Particle Source
# you can do a lot more with this than a monoenergetic, monodirectional, single-particle gun
# for a full list of /gps/ commands see:
# https://geant4.web.cern.ch/geant4/UserDocumentation/UsersGuides/ForApplicationDeveloper/html/ch02s07.html
/mygen/generator gps
/gps/particle gamma
/gps/energy 20 MeV
/gps/ang/type iso
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/radius 150 cm
/gps/pos/halfz 100 cm

# Needed to prevent other decay than Bi-214
/grdm/nucleusLimits 214 214 83 83 
# if you need to use time bias
#/grdm/decayBiasProfile biasprofile.dat
#/grdm/analogueMC 0
#/grdm/BRbias 0

/WCSimIO/RootFile sns_30pc_gamma_20MeV_Uni.root
## set a timer running on WCSimRunAction
#/WCSimIO/Timer false

/run/beamOn 3000
#exit
